// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Generated bindings for the stable AbzarFile C ABI.
class AbzarBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AbzarBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AbzarBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int abz_abi_version() {
    return _abz_abi_version();
  }

  late final _abz_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>('abz_abi_version');
  late final _abz_abi_version =
      _abz_abi_versionPtr.asFunction<int Function()>();

  ffi.Pointer<ffi.Char> abz_engine_version() {
    return _abz_engine_version();
  }

  late final _abz_engine_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'abz_engine_version');
  late final _abz_engine_version =
      _abz_engine_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> abz_build_features() {
    return _abz_build_features();
  }

  late final _abz_build_featuresPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'abz_build_features');
  late final _abz_build_features =
      _abz_build_featuresPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  int abz_is_format_supported(
    ffi.Pointer<ffi.Char> extension_utf8,
    int for_export,
  ) {
    return _abz_is_format_supported(
      extension_utf8,
      for_export,
    );
  }

  late final _abz_is_format_supportedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>, ffi.Int32)>>('abz_is_format_supported');
  late final _abz_is_format_supported = _abz_is_format_supportedPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<AbzJob> abz_job_create(
    ffi.Pointer<ffi.Char> specification_json_utf8,
  ) {
    return _abz_job_create(
      specification_json_utf8,
    );
  }

  late final _abz_job_createPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<AbzJob> Function(ffi.Pointer<ffi.Char>)>>(
      'abz_job_create');
  late final _abz_job_create = _abz_job_createPtr
      .asFunction<ffi.Pointer<AbzJob> Function(ffi.Pointer<ffi.Char>)>();

  int abz_job_run(
    ffi.Pointer<AbzJob> job,
    AbzProgressCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _abz_job_run(
      job,
      callback,
      user_data,
    );
  }

  late final _abz_job_runPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AbzJob>, AbzProgressCallback,
              ffi.Pointer<ffi.Void>)>>('abz_job_run');
  late final _abz_job_run = _abz_job_runPtr.asFunction<
      int Function(
          ffi.Pointer<AbzJob>, AbzProgressCallback, ffi.Pointer<ffi.Void>)>();

  void abz_job_cancel(
    ffi.Pointer<AbzJob> job,
  ) {
    return _abz_job_cancel(
      job,
    );
  }

  late final _abz_job_cancelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<AbzJob>)>>(
          'abz_job_cancel');
  late final _abz_job_cancel =
      _abz_job_cancelPtr.asFunction<void Function(ffi.Pointer<AbzJob>)>();

  int abz_job_report(
    ffi.Pointer<AbzJob> job,
    ffi.Pointer<AbzJobReport> report,
  ) {
    return _abz_job_report(
      job,
      report,
    );
  }

  late final _abz_job_reportPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<AbzJob>,
              ffi.Pointer<AbzJobReport>)>>('abz_job_report');
  late final _abz_job_report = _abz_job_reportPtr.asFunction<
      int Function(ffi.Pointer<AbzJob>, ffi.Pointer<AbzJobReport>)>();

  ffi.Pointer<ffi.Char> abz_job_error_message(
    ffi.Pointer<AbzJob> job,
  ) {
    return _abz_job_error_message(
      job,
    );
  }

  late final _abz_job_error_messagePtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AbzJob>)>>(
      'abz_job_error_message');
  late final _abz_job_error_message = _abz_job_error_messagePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AbzJob>)>();

  ffi.Pointer<ffi.Char> abz_job_report_json(
    ffi.Pointer<AbzJob> job,
  ) {
    return _abz_job_report_json(
      job,
    );
  }

  late final _abz_job_report_jsonPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AbzJob>)>>(
      'abz_job_report_json');
  late final _abz_job_report_json = _abz_job_report_jsonPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AbzJob>)>();

  void abz_job_destroy(
    ffi.Pointer<AbzJob> job,
  ) {
    return _abz_job_destroy(
      job,
    );
  }

  late final _abz_job_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<AbzJob>)>>(
          'abz_job_destroy');
  late final _abz_job_destroy =
      _abz_job_destroyPtr.asFunction<void Function(ffi.Pointer<AbzJob>)>();

  int abz_convert_file(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Char> source_format_utf8,
    ffi.Pointer<ffi.Char> target_format_utf8,
    ffi.Pointer<ffi.Char> options_json_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_convert_file(
      input_path_utf8,
      output_path_utf8,
      source_format_utf8,
      target_format_utf8,
      options_json_utf8,
      error_utf8,
    );
  }

  late final _abz_convert_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_convert_file');
  late final _abz_convert_file = _abz_convert_filePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_compress_file(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Char> format_utf8,
    int level,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_compress_file(
      input_path_utf8,
      output_path_utf8,
      format_utf8,
      level,
      error_utf8,
    );
  }

  late final _abz_compress_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_compress_file');
  late final _abz_compress_file = _abz_compress_filePtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_merge_files(
    ffi.Pointer<ffi.Char> input_paths_json_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Char> source_format_utf8,
    ffi.Pointer<ffi.Char> target_format_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_merge_files(
      input_paths_json_utf8,
      output_path_utf8,
      source_format_utf8,
      target_format_utf8,
      error_utf8,
    );
  }

  late final _abz_merge_filesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_merge_files');
  late final _abz_merge_files = _abz_merge_filesPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_split_file(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_directory_utf8,
    ffi.Pointer<ffi.Char> format_utf8,
    ffi.Pointer<ffi.Char> ranges_json_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> outputs_json_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_split_file(
      input_path_utf8,
      output_directory_utf8,
      format_utf8,
      ranges_json_utf8,
      outputs_json_utf8,
      error_utf8,
    );
  }

  late final _abz_split_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_split_file');
  late final _abz_split_file = _abz_split_filePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_extract_text(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> source_format_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> text_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_extract_text(
      input_path_utf8,
      source_format_utf8,
      text_utf8,
      error_utf8,
    );
  }

  late final _abz_extract_textPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_extract_text');
  late final _abz_extract_text = _abz_extract_textPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_encrypt_container(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Char> password_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_encrypt_container(
      input_path_utf8,
      output_path_utf8,
      password_utf8,
      error_utf8,
    );
  }

  late final _abz_encrypt_containerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_encrypt_container');
  late final _abz_encrypt_container = _abz_encrypt_containerPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_decrypt_container(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Char> password_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_decrypt_container(
      input_path_utf8,
      output_path_utf8,
      password_utf8,
      error_utf8,
    );
  }

  late final _abz_decrypt_containerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_decrypt_container');
  late final _abz_decrypt_container = _abz_decrypt_containerPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_replace_text(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Char> search_utf8,
    ffi.Pointer<ffi.Char> replacement_utf8,
    int page_index,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_replace_text(
      input_path_utf8,
      output_path_utf8,
      search_utf8,
      replacement_utf8,
      page_index,
      error_utf8,
    );
  }

  late final _abz_pdf_replace_textPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_replace_text');
  late final _abz_pdf_replace_text = _abz_pdf_replace_textPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_delete_image(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    int page_index,
    ffi.Pointer<ffi.Char> object_name_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_delete_image(
      input_path_utf8,
      output_path_utf8,
      page_index,
      object_name_utf8,
      error_utf8,
    );
  }

  late final _abz_pdf_delete_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_delete_image');
  late final _abz_pdf_delete_image = _abz_pdf_delete_imagePtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_add_image(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    int page_index,
    ffi.Pointer<ffi.Char> image_path_utf8,
    ffi.Pointer<ffi.Char> image_format_utf8,
    double x,
    double y,
    double width,
    double height,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_add_image(
      input_path_utf8,
      output_path_utf8,
      page_index,
      image_path_utf8,
      image_format_utf8,
      x,
      y,
      width,
      height,
      error_utf8,
    );
  }

  late final _abz_pdf_add_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Double,
              ffi.Double,
              ffi.Double,
              ffi.Double,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_add_image');
  late final _abz_pdf_add_image = _abz_pdf_add_imagePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          double,
          double,
          double,
          double,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_replace_image(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    int page_index,
    ffi.Pointer<ffi.Char> object_name_utf8,
    ffi.Pointer<ffi.Char> replacement_path_utf8,
    ffi.Pointer<ffi.Char> replacement_format_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_replace_image(
      input_path_utf8,
      output_path_utf8,
      page_index,
      object_name_utf8,
      replacement_path_utf8,
      replacement_format_utf8,
      error_utf8,
    );
  }

  late final _abz_pdf_replace_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_replace_image');
  late final _abz_pdf_replace_image = _abz_pdf_replace_imagePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_flatten(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_flatten(
      input_path_utf8,
      output_path_utf8,
      error_utf8,
    );
  }

  late final _abz_pdf_flattenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_flatten');
  late final _abz_pdf_flatten = _abz_pdf_flattenPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_add_bookmark(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    int page_index,
    ffi.Pointer<ffi.Char> title_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_add_bookmark(
      input_path_utf8,
      output_path_utf8,
      page_index,
      title_utf8,
      error_utf8,
    );
  }

  late final _abz_pdf_add_bookmarkPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_add_bookmark');
  late final _abz_pdf_add_bookmark = _abz_pdf_add_bookmarkPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_add_annotation(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    int page_index,
    ffi.Pointer<ffi.Char> text_utf8,
    double x,
    double y,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_add_annotation(
      input_path_utf8,
      output_path_utf8,
      page_index,
      text_utf8,
      x,
      y,
      error_utf8,
    );
  }

  late final _abz_pdf_add_annotationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Double,
              ffi.Double,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_add_annotation');
  late final _abz_pdf_add_annotation = _abz_pdf_add_annotationPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          double,
          double,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_repair(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_repair(
      input_path_utf8,
      output_path_utf8,
      error_utf8,
    );
  }

  late final _abz_pdf_repairPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_repair');
  late final _abz_pdf_repair = _abz_pdf_repairPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_set_password(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Char> user_password_utf8,
    ffi.Pointer<ffi.Char> owner_password_utf8,
    int allow_print,
    int allow_copy,
    int allow_modify,
    int allow_annotate,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_set_password(
      input_path_utf8,
      output_path_utf8,
      user_password_utf8,
      owner_password_utf8,
      allow_print,
      allow_copy,
      allow_modify,
      allow_annotate,
      error_utf8,
    );
  }

  late final _abz_pdf_set_passwordPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Int32,
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_set_password');
  late final _abz_pdf_set_password = _abz_pdf_set_passwordPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          int,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_pdf_remove_password(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Char> password_utf8,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_pdf_remove_password(
      input_path_utf8,
      output_path_utf8,
      password_utf8,
      error_utf8,
    );
  }

  late final _abz_pdf_remove_passwordPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_pdf_remove_password');
  late final _abz_pdf_remove_password = _abz_pdf_remove_passwordPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int abz_process_scan_image(
    ffi.Pointer<ffi.Char> input_path_utf8,
    ffi.Pointer<ffi.Char> output_path_utf8,
    ffi.Pointer<ffi.Char> format_utf8,
    int perspective,
    int filter,
    double brightness,
    double contrast,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_utf8,
  ) {
    return _abz_process_scan_image(
      input_path_utf8,
      output_path_utf8,
      format_utf8,
      perspective,
      filter,
      brightness,
      contrast,
      error_utf8,
    );
  }

  late final _abz_process_scan_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Int32,
              ffi.Double,
              ffi.Double,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('abz_process_scan_image');
  late final _abz_process_scan_image = _abz_process_scan_imagePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          double,
          double,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  void abz_free(
    ffi.Pointer<ffi.Void> memory,
  ) {
    return _abz_free(
      memory,
    );
  }

  late final _abz_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'abz_free');
  late final _abz_free =
      _abz_freePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}

enum AbzErrorCode {
  ABZ_OK(0),
  ABZ_ERROR_INVALID_ARGUMENT(1),
  ABZ_ERROR_IO(2),
  ABZ_ERROR_UNSUPPORTED_FORMAT(3),
  ABZ_ERROR_CORRUPT_INPUT(4),
  ABZ_ERROR_PASSWORD_REQUIRED(5),
  ABZ_ERROR_WRONG_PASSWORD(6),
  ABZ_ERROR_OCR_UNAVAILABLE(7),
  ABZ_ERROR_CANCELLED(8),
  ABZ_ERROR_OUT_OF_MEMORY(9),
  ABZ_ERROR_INTERNAL(10),
  ABZ_ERROR_VALIDATION(11);

  final int value;
  const AbzErrorCode(this.value);

  static AbzErrorCode fromValue(int value) => switch (value) {
        0 => ABZ_OK,
        1 => ABZ_ERROR_INVALID_ARGUMENT,
        2 => ABZ_ERROR_IO,
        3 => ABZ_ERROR_UNSUPPORTED_FORMAT,
        4 => ABZ_ERROR_CORRUPT_INPUT,
        5 => ABZ_ERROR_PASSWORD_REQUIRED,
        6 => ABZ_ERROR_WRONG_PASSWORD,
        7 => ABZ_ERROR_OCR_UNAVAILABLE,
        8 => ABZ_ERROR_CANCELLED,
        9 => ABZ_ERROR_OUT_OF_MEMORY,
        10 => ABZ_ERROR_INTERNAL,
        11 => ABZ_ERROR_VALIDATION,
        _ => throw ArgumentError("Unknown value for AbzErrorCode: $value"),
      };
}

enum AbzJobState {
  ABZ_JOB_CREATED(0),
  ABZ_JOB_RUNNING(1),
  ABZ_JOB_SUCCEEDED(2),
  ABZ_JOB_FAILED(3),
  ABZ_JOB_CANCELLED(4);

  final int value;
  const AbzJobState(this.value);

  static AbzJobState fromValue(int value) => switch (value) {
        0 => ABZ_JOB_CREATED,
        1 => ABZ_JOB_RUNNING,
        2 => ABZ_JOB_SUCCEEDED,
        3 => ABZ_JOB_FAILED,
        4 => ABZ_JOB_CANCELLED,
        _ => throw ArgumentError("Unknown value for AbzJobState: $value"),
      };
}

final class AbzJob extends ffi.Opaque {}

final class AbzJobReport extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Int32()
  external int error_code;

  @ffi.Int32()
  external int state;

  @ffi.Uint64()
  external int input_bytes;

  @ffi.Uint64()
  external int output_bytes;

  @ffi.Uint64()
  external int duration_ms;

  @ffi.Uint32()
  external int page_count;

  @ffi.Uint32()
  external int warning_count;
}

typedef AbzProgressCallbackFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void> user_data,
    ffi.Double progress,
    ffi.Pointer<ffi.Char> stage_utf8);
typedef DartAbzProgressCallbackFunction = void Function(
    ffi.Pointer<ffi.Void> user_data,
    double progress,
    ffi.Pointer<ffi.Char> stage_utf8);
typedef AbzProgressCallback
    = ffi.Pointer<ffi.NativeFunction<AbzProgressCallbackFunction>>;

const int ABZAR_ABI_VERSION = 1;
