#include <algorithm>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <string>
#include <vector>
#include "abzar/abzar_api.h"
namespace {
void require(bool condition,const std::string& message){if(!condition){std::cerr<<"FAIL: "<<message<<'\n';std::exit(1);}}
std::vector<unsigned char> read(const std::filesystem::path& path){std::ifstream in(path,std::ios::binary|std::ios::ate);require(bool(in),"open "+path.string());const auto n=in.tellg();std::vector<unsigned char>b(static_cast<std::size_t>(n));in.seekg(0);in.read(reinterpret_cast<char*>(b.data()),n);return b;}
void convert(const std::filesystem::path& in,const std::filesystem::path& out,const char* source,const char* target){char* error=nullptr;const auto code=abz_convert_file(in.string().c_str(),out.string().c_str(),source,target,"{\"dpi\":72}",&error);if(code!=ABZ_OK){std::cerr<<"Conversion failed: "<<(error?error:"")<<'\n';abz_free(error);std::exit(1);}abz_free(error);}
bool contains(const std::vector<unsigned char>& b,const std::string& text){return std::search(b.begin(),b.end(),text.begin(),text.end())!=b.end();}
}
int main(){require(abz_abi_version()==ABZAR_ABI_VERSION,"ABI version");const std::string features=abz_build_features();require(features.find("\"qpdf\":")!=std::string::npos&&features.find("\"textShaping\":")!=std::string::npos,"native feature manifest");if(std::getenv("ABZAR_REQUIRE_FULL_FEATURES")){for(const auto* feature:{"pdfium","qpdf","ocr","opencv","textShaping","fontSubsetting"})require(features.find("\""+std::string(feature)+"\":true")!=std::string::npos,"required native feature "+std::string(feature));}const auto root=std::filesystem::temp_directory_path()/"abzar-core-tests";std::filesystem::remove_all(root);std::filesystem::create_directories(root);const auto input=root/"source.txt";{std::ofstream out(input);out<<"AbzarFile real conversion\nSecond paragraph\n42";}
char* extracted=nullptr;char* operation_error=nullptr;require(abz_extract_text(input.string().c_str(),"txt",&extracted,&operation_error)==ABZ_OK,"extract text operation");require(std::string(extracted).find("AbzarFile")!=std::string::npos,"extracted semantic text");abz_free(extracted);abz_free(operation_error);
const auto archive=root/"compressed.abz";require(abz_compress_file(input.string().c_str(),archive.string().c_str(),"txt",10,&operation_error)==ABZ_OK,"compress operation");auto archive_bytes=read(archive);require(archive_bytes.size()>21&&std::string(archive_bytes.begin(),archive_bytes.begin()+4)=="ABZ1","ABZ archive header");abz_free(operation_error);std::size_t previous_size=std::numeric_limits<std::size_t>::max();for(int level=1;level<=10;++level){const auto level_output=root/("level-"+std::to_string(level)+".abz");require(abz_compress_file(input.string().c_str(),level_output.string().c_str(),"txt",level,&operation_error)==ABZ_OK,"compression level operation");const auto current_size=read(level_output).size();require(current_size<previous_size,"ten compression levels strictly decrease");previous_size=current_size;abz_free(operation_error);}
const auto merged=root/"merged.txt";const std::string paths="[\""+input.string()+"\",\""+input.string()+"\"]";require(abz_merge_files(paths.c_str(),merged.string().c_str(),"txt","txt",&operation_error)==ABZ_OK,"merge operation");require(contains(read(merged),"Second paragraph"),"merged text content");abz_free(operation_error);
const auto encrypted=root/"secret.abze";const auto decrypted=root/"decrypted.txt";auto crypto_code=abz_encrypt_container(input.string().c_str(),encrypted.string().c_str(),"correct horse battery staple",&operation_error);if(crypto_code==ABZ_OK){require(abz_decrypt_container(encrypted.string().c_str(),decrypted.string().c_str(),"correct horse battery staple",&operation_error)==ABZ_OK,"AES container decrypt");require(read(decrypted)==read(input),"AES container round trip");abz_free(operation_error);const auto wrong=root/"wrong.txt";require(abz_decrypt_container(encrypted.string().c_str(),wrong.string().c_str(),"wrong password",&operation_error)==ABZ_ERROR_WRONG_PASSWORD,"AES rejects wrong password");abz_free(operation_error);}else{require(crypto_code==ABZ_ERROR_UNSUPPORTED_FORMAT,"crypto capability reports typed unavailable status");abz_free(operation_error);}
const auto pdf=root/"out.pdf";convert(input,pdf,"txt","pdf");auto bytes=read(pdf);require(bytes.size()>200&&std::string(bytes.begin(),bytes.begin()+5)=="%PDF-","PDF header");require(contains(bytes,"xref")&&contains(bytes,"trailer")&&contains(bytes,"AbzarFile real conversion"),"PDF structure and selectable text");
const auto flattened_pdf=root/"flattened.pdf";auto structure_code=abz_pdf_flatten(pdf.string().c_str(),flattened_pdf.string().c_str(),&operation_error);if(structure_code==ABZ_OK)require(read(flattened_pdf).size()>100,"PDF form flatten output");else require(structure_code==ABZ_ERROR_UNSUPPORTED_FORMAT,"PDF flatten typed availability");abz_free(operation_error);const auto bookmarked_pdf=root/"bookmarked.pdf";structure_code=abz_pdf_add_bookmark(pdf.string().c_str(),bookmarked_pdf.string().c_str(),0,"Fixture bookmark",&operation_error);if(structure_code==ABZ_OK)require(read(bookmarked_pdf).size()>100,"PDF bookmark output");else require(structure_code==ABZ_ERROR_UNSUPPORTED_FORMAT,"PDF outline typed availability");abz_free(operation_error);const auto annotated_pdf=root/"annotated.pdf";structure_code=abz_pdf_add_annotation(pdf.string().c_str(),annotated_pdf.string().c_str(),0,"Fixture annotation",36,760,&operation_error);if(structure_code==ABZ_OK)require(read(annotated_pdf).size()>100,"PDF annotation output");else require(structure_code==ABZ_ERROR_UNSUPPORTED_FORMAT,"PDF annotation typed availability");abz_free(operation_error);
const auto edited_text_pdf=root/"text-edited.pdf";auto text_edit_code=abz_pdf_replace_text(pdf.string().c_str(),edited_text_pdf.string().c_str(),"real conversion","object editing",-1,&operation_error);if(text_edit_code==ABZ_OK){const auto edited_bytes=read(edited_text_pdf);require(edited_bytes.size()>5&&std::string(edited_bytes.begin(),edited_bytes.begin()+5)=="%PDF-","PDF text-object edit output");}else require(text_edit_code==ABZ_ERROR_UNSUPPORTED_FORMAT,"PDF text editor typed availability");abz_free(operation_error);
const auto protected_pdf=root/"protected.pdf";auto pdf_security=abz_pdf_set_password(pdf.string().c_str(),protected_pdf.string().c_str(),"reader-password","owner-password",1,0,0,1,&operation_error);if(pdf_security==ABZ_OK){require(read(protected_pdf).size()>100,"PDF AES-256 output");const auto open_pdf=root/"unprotected.pdf";require(abz_pdf_remove_password(protected_pdf.string().c_str(),open_pdf.string().c_str(),"reader-password",&operation_error)==ABZ_OK,"PDF password removal");const auto opened_bytes=read(open_pdf);require(opened_bytes.size()>5&&std::string(opened_bytes.begin(),opened_bytes.begin()+5)=="%PDF-","decrypted PDF validity");abz_free(operation_error);}else{require(pdf_security==ABZ_ERROR_UNSUPPORTED_FORMAT,"PDF security typed availability");abz_free(operation_error);}
for(const auto* format:{"docx","xlsx","pptx"}){const auto output=root/(std::string("out.")+format);convert(input,output,"txt",format);bytes=read(output);require(bytes.size()>200&&bytes[0]=='P'&&bytes[1]=='K',std::string(format)+" ZIP signature");require(contains(bytes,"[Content_Types].xml"),std::string(format)+" content types");const auto exact=root/(std::string("roundtrip.")+format);convert(output,exact,format,format);require(read(exact)==read(output),std::string(format)+" exact package round trip");convert(output,root/(std::string(format)+".txt"),format,"txt");require(contains(read(root/(std::string(format)+".txt")),"AbzarFile"),std::string(format)+" text round trip");}
require(contains(read(root/"out.pptx"),"ppt/media/image1.png")&&contains(read(root/"out.pptx"),"relationships/image"),"PPTX image-backed slide with text layer");
const auto compact_docx=root/"compact.docx";require(abz_compress_file((root/"out.docx").string().c_str(),compact_docx.string().c_str(),"docx",10,&operation_error)==ABZ_OK,"OOXML recompression");convert(compact_docx,root/"compact.txt","docx","txt");require(contains(read(root/"compact.txt"),"AbzarFile"),"recompressed OOXML remains readable");abz_free(operation_error);
const auto merged_xlsx=root/"merged.xlsx";const std::string xlsx_inputs="[\""+(root/"out.xlsx").string()+"\",\""+(root/"out.xlsx").string()+"\"]";require(abz_merge_files(xlsx_inputs.c_str(),merged_xlsx.string().c_str(),"xlsx","xlsx",&operation_error)==ABZ_OK,"XLSX multi-sheet merge");abz_free(operation_error);char* sheet_outputs=nullptr;require(abz_split_file(merged_xlsx.string().c_str(),(root/"sheets").string().c_str(),"xlsx","[]",&sheet_outputs,&operation_error)==ABZ_OK,"XLSX split by sheet");const std::string sheet_output_json(sheet_outputs);require(std::count(sheet_output_json.begin(),sheet_output_json.end(),'.')>=2,"XLSX split output list");abz_free(sheet_outputs);abz_free(operation_error);
char* split_outputs=nullptr;const auto split_dir=root/"split";const auto docx_for_split=root/"out.docx";require(abz_split_file(docx_for_split.string().c_str(),split_dir.string().c_str(),"docx","[]",&split_outputs,&operation_error)==ABZ_OK,"split operation");require(split_outputs!=nullptr&&std::string(split_outputs).find(".docx")!=std::string::npos,"split output report");abz_free(split_outputs);abz_free(operation_error);
const auto html=root/"out.html";convert(input,html,"txt","html");require(contains(read(html),"<!doctype html>")&&contains(read(html),"AbzarFile"),"HTML output");
const auto png=root/"out.png";convert(input,png,"txt","png");bytes=read(png);const unsigned char signature[]={137,80,78,71,13,10,26,10};require(bytes.size()>100&&std::equal(std::begin(signature),std::end(signature),bytes.begin()),"PNG signature");require(contains(bytes,"IHDR")&&contains(bytes,"IDAT")&&contains(bytes,"IEND"),"PNG chunks");
const auto jpeg=root/"out.jpg";convert(input,jpeg,"txt","jpg");bytes=read(jpeg);require(bytes.size()>100&&bytes[0]==0xff&&bytes[1]==0xd8&&bytes[bytes.size()-2]==0xff&&bytes.back()==0xd9,"JPEG encoding");const auto jpeg_png=root/"jpeg.png";convert(jpeg,jpeg_png,"jpg","png");require(read(jpeg_png)[0]==137,"JPEG decode and raster conversion");
const auto added_image_pdf=root/"image-added.pdf";auto image_add_code=abz_pdf_add_image(pdf.string().c_str(),added_image_pdf.string().c_str(),0,png.string().c_str(),"png",36,36,144,144,&operation_error);if(image_add_code==ABZ_OK)require(read(added_image_pdf).size()>read(pdf).size(),"PDF image object addition");else require(image_add_code==ABZ_ERROR_UNSUPPORTED_FORMAT,"PDF image editor typed availability");abz_free(operation_error);
const auto image_pdf=root/"image.pdf";convert(png,image_pdf,"png","pdf");bytes=read(image_pdf);require(contains(bytes,"/Subtype /Image")&&contains(bytes,"/Im1 Do"),"PNG pixels embedded into PDF page");const auto replaced_image_pdf=root/"image-replaced.pdf";auto image_replace_code=abz_pdf_replace_image(image_pdf.string().c_str(),replaced_image_pdf.string().c_str(),0,"Im1",png.string().c_str(),"png",&operation_error);if(image_replace_code==ABZ_OK)require(read(replaced_image_pdf).size()>100,"PDF image object replacement");else require(image_replace_code==ABZ_ERROR_UNSUPPORTED_FORMAT,"PDF replacement typed availability");abz_free(operation_error);
const std::vector<std::pair<std::string,std::filesystem::path>> sources={{"txt",input},{"html",html},{"pdf",pdf},{"docx",root/"out.docx"},{"xlsx",root/"out.xlsx"},{"pptx",root/"out.pptx"},{"png",png},{"jpg",jpeg}};const std::vector<std::string> targets={"docx","xlsx","pptx","pdf","html","txt","png","jpg"};for(const auto& [source_format,source_path]:sources){for(const auto& target:targets){const bool raster_source=source_format=="png"||source_format=="jpg";if(raster_source&&target!="pdf"&&target!="png"&&target!="jpg")continue;const auto pair_output=root/("matrix-"+source_format+"-"+target+"."+target);convert(source_path,pair_output,source_format.c_str(),target.c_str());const auto pair_bytes=read(pair_output);if(target=="pdf")require(pair_bytes.size()>5&&std::string(pair_bytes.begin(),pair_bytes.begin()+5)=="%PDF-","matrix PDF structure");else if(target=="docx"||target=="xlsx"||target=="pptx")require(pair_bytes.size()>4&&pair_bytes[0]=='P'&&pair_bytes[1]=='K'&&contains(pair_bytes,"[Content_Types].xml"),"matrix OOXML structure");else if(target=="png")require(pair_bytes.size()>8&&pair_bytes[0]==137&&contains(pair_bytes,"IDAT"),"matrix PNG structure");else if(target=="jpg")require(pair_bytes.size()>4&&pair_bytes[0]==0xff&&pair_bytes[1]==0xd8,"matrix JPEG structure");else require(!pair_bytes.empty(),"matrix text structure");}}
std::cout<<"All native structural conversion tests passed\n";std::filesystem::remove_all(root);return 0;}
