#include "util/string.h"
#include <algorithm>
#include <cctype>
#include <iomanip>
#include <sstream>
namespace abzar::strings {
std::string lower(std::string value) { std::transform(value.begin(),value.end(),value.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));}); return value; }
std::string trim(std::string value) { const auto a=value.find_first_not_of(" \t\r\n"); if(a==std::string::npos)return {}; const auto b=value.find_last_not_of(" \t\r\n"); return value.substr(a,b-a+1); }
std::string xml_escape(std::string_view v) { std::string o; for(char c:v){switch(c){case '&':o+="&amp;";break;case '<':o+="&lt;";break;case '>':o+="&gt;";break;case '\"':o+="&quot;";break;case '\'':o+="&apos;";break;default:o+=c;}} return o; }
std::string html_escape(std::string_view v) { return xml_escape(v); }
std::string json_escape(std::string_view v) { std::ostringstream o; for(unsigned char c:v){switch(c){case '\\':o<<"\\\\";break;case '"':o<<"\\\"";break;case '\n':o<<"\\n";break;case '\r':o<<"\\r";break;case '\t':o<<"\\t";break;default:if(c<32)o<<"\\u"<<std::hex<<std::setw(4)<<std::setfill('0')<<int(c);else o<<c;}} return o.str(); }
namespace {
std::string decode_entities(std::string value) { const std::pair<const char*,const char*> pairs[]={{"&amp;","&"},{"&lt;","<"},{"&gt;",">"},{"&quot;","\""},{"&apos;","'"},{"&#39;","'"},{"&nbsp;"," "}}; for(auto [a,b]:pairs){std::size_t p=0;while((p=value.find(a,p))!=std::string::npos){value.replace(p,std::char_traits<char>::length(a),b);p+=std::char_traits<char>::length(b);}}return value; }
}
std::string strip_xml(std::string_view xml) { std::string out; bool tag=false; for(std::size_t i=0;i<xml.size();++i){char c=xml[i];if(c=='<'){tag=true;if(i+3<xml.size()&&(xml.substr(i,4)=="</w:p"||xml.substr(i,4)=="</a:p"))out+='\n';}else if(c=='>')tag=false;else if(!tag)out+=c;} return trim(decode_entities(out)); }
std::string strip_html(std::string_view html) { std::string out; bool tag=false; std::string current; for(std::size_t i=0;i<html.size();++i){char c=html[i];if(c=='<'){tag=true;current.clear();}else if(c=='>'){tag=false;auto t=lower(trim(current));if(t=="br"||t=="br/"||t=="/p"||t=="/div"||t=="/li"||t=="/h1"||t=="/h2"||t=="/tr")out+='\n';else if(t=="/td"||t=="/th")out+='\t';}else if(tag)current+=c;else out+=c;}return trim(decode_entities(out)); }
std::vector<std::string> split_lines(std::string_view v){std::vector<std::string> lines;std::string line;for(char c:v){if(c=='\n'){if(!line.empty()&&line.back()=='\r')line.pop_back();lines.push_back(line);line.clear();}else line+=c;}lines.push_back(line);return lines;}
std::string normalize_text_encoding(const std::vector<unsigned char>& b){ if(b.size()>=3&&b[0]==0xef&&b[1]==0xbb&&b[2]==0xbf)return {reinterpret_cast<const char*>(b.data()+3),b.size()-3}; if(b.size()>=2&&((b[0]==0xff&&b[1]==0xfe)||(b[0]==0xfe&&b[1]==0xff))){bool le=b[0]==0xff;std::string o;for(std::size_t i=2;i+1<b.size();i+=2){unsigned cp=le?(b[i]|(b[i+1]<<8)):(b[i+1]|(b[i]<<8));if(cp<0x80)o+=char(cp);else if(cp<0x800){o+=char(0xc0|(cp>>6));o+=char(0x80|(cp&63));}else{o+=char(0xe0|(cp>>12));o+=char(0x80|((cp>>6)&63));o+=char(0x80|(cp&63));}}return o;} return {reinterpret_cast<const char*>(b.data()),b.size()}; }
std::string json_string(std::string_view j,std::string_view key){const std::string needle="\""+std::string(key)+"\"";auto p=j.find(needle);if(p==std::string_view::npos)return {};p=j.find(':',p+needle.size());if(p==std::string_view::npos)return {};p=j.find('"',p+1);if(p==std::string_view::npos)return {};std::string o;for(++p;p<j.size();++p){char c=j[p];if(c=='"')break;if(c=='\\'&&p+1<j.size()){char n=j[++p];if(n=='n')o+='\n';else if(n=='t')o+='\t';else o+=n;}else o+=c;}return o;}
int json_integer(std::string_view j,std::string_view key,int f){const auto n="\""+std::string(key)+"\"";auto p=j.find(n);if(p==j.npos)return f;p=j.find(':',p+n.size());if(p==j.npos)return f;try{return std::stoi(std::string(j.substr(p+1)));}catch(...){return f;}}
bool json_boolean(std::string_view j,std::string_view key,bool f){const auto n="\""+std::string(key)+"\"";auto p=j.find(n);if(p==j.npos)return f;p=j.find(':',p+n.size());if(p==j.npos)return f;auto tail=j.substr(p+1);auto t=tail.find("true"),q=tail.find("false");if(t!=tail.npos&&(q==tail.npos||t<q))return true;if(q!=tail.npos)return false;return f;}
std::vector<std::string> json_string_array(std::string_view json){std::vector<std::string> values;bool in_string=false,escaped=false;std::string value;for(char c:json){if(!in_string){if(c=='\"'){in_string=true;value.clear();}continue;}if(escaped){switch(c){case 'n':value+='\n';break;case 'r':value+='\r';break;case 't':value+='\t';break;default:value+=c;}escaped=false;}else if(c=='\\')escaped=true;else if(c=='\"'){values.push_back(value);in_string=false;}else value+=c;}return values;}
}  // namespace abzar::strings
