#include "exporters/exporter.h"
#include <algorithm>
#include <iomanip>
#include <sstream>
#include "core/error.h"
#include "util/fs.h"
#include <zlib.h>
namespace abzar {
namespace {
std::string pdf_escape(const std::string& s){std::string o;for(unsigned char c:s){if(c=='('||c==')'||c=='\\')o+='\\';if(c=='\r')continue;o+=c=='\n'?' ':char(c);}return o;}
std::vector<std::uint8_t> deflate(const std::vector<std::uint8_t>& raw){std::vector<std::uint8_t> out(compressBound(raw.size()));uLongf n=out.size();if(compress2(out.data(),&n,raw.data(),raw.size(),9)!=Z_OK)throw Error(ABZ_ERROR_INTERNAL,"PDF image compression failed");out.resize(n);return out;}
struct Object{std::vector<std::uint8_t> bytes;};
Object page_content(const std::string& text,bool draw_image,double width,double height){std::ostringstream stream;if(draw_image)stream<<"q\n"<<width<<" 0 0 "<<height<<" 0 0 cm\n/Im1 Do\nQ\n";stream<<"BT\n/F1 11 Tf\n54 "<<height-62<<" Td\n14 TL\n";std::size_t lines=0;std::string line;for(char c:text){if(c=='\n'||line.size()>90){stream<<"("<<pdf_escape(line)<<") Tj\nT*\n";line.clear();if(++lines>50)break;}else line+=c;}if(!line.empty())stream<<"("<<pdf_escape(line)<<") Tj\n";stream<<"ET\n";const auto s=stream.str();std::ostringstream head;head<<"<< /Length "<<s.size()<<" >>\nstream\n"<<s<<"endstream";const auto all=head.str();return {{all.begin(),all.end()}};}
}
void export_pdf(const Document& d,const std::filesystem::path& path){std::vector<const Page*> pages;for(const auto& s:d.sections)for(const auto& p:s.pages)pages.push_back(&p);if(pages.empty())throw Error(ABZ_ERROR_VALIDATION,"Document has no pages");std::vector<Object> objects;auto add=[&](Object o){objects.push_back(std::move(o));return int(objects.size());};const int catalog=add({});const int page_tree=add({});const int font=add({{'<','<',' ','/','T','y','p','e',' ','/','F','o','n','t',' ','/','S','u','b','t','y','p','e',' ','/','T','y','p','e','1',' ','/','B','a','s','e','F','o','n','t',' ','/','H','e','l','v','e','t','i','c','a',' ','>','>'}});std::vector<int> page_ids;for(const auto* page:pages){int image_id=0;for(const auto& b:page->blocks)if(b.image){const auto& image=*b.image;if(image.mime_type=="image/jpeg"){std::ostringstream h;h<<"<< /Type /XObject /Subtype /Image /Width "<<image.width<<" /Height "<<image.height<<" /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length "<<image.encoded.size()<<" >>\nstream\n";auto hs=h.str();std::vector<std::uint8_t> bytes(hs.begin(),hs.end());bytes.insert(bytes.end(),image.encoded.begin(),image.encoded.end());const std::string tail="\nendstream";bytes.insert(bytes.end(),tail.begin(),tail.end());image_id=add({std::move(bytes)});}else if(!image.rgba.empty()){std::vector<std::uint8_t> rgb;rgb.reserve(std::size_t(image.width)*image.height*3);for(std::size_t i=0;i<image.rgba.size();i+=4){const auto a=image.rgba[i+3];for(int c=0;c<3;++c)rgb.push_back(static_cast<unsigned char>((image.rgba[i+c]*a+255*(255-a))/255));}auto packed=deflate(rgb);std::ostringstream h;h<<"<< /Type /XObject /Subtype /Image /Width "<<image.width<<" /Height "<<image.height<<" /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /FlateDecode /Length "<<packed.size()<<" >>\nstream\n";auto hs=h.str();std::vector<std::uint8_t> bytes(hs.begin(),hs.end());bytes.insert(bytes.end(),packed.begin(),packed.end());const std::string tail="\nendstream";bytes.insert(bytes.end(),tail.begin(),tail.end());image_id=add({std::move(bytes)});}break;}const auto content=add(page_content([&]{std::string text;for(const auto& block:page->blocks)for(const auto& run:block.runs)text+=run.text+'\n';return text;}(),image_id!=0,page->geometry.width_points,page->geometry.height_points));std::ostringstream dict;dict<<"<< /Type /Page /Parent "<<page_tree<<" 0 R /MediaBox [0 0 "<<page->geometry.width_points<<' '<<page->geometry.height_points<<"] /Resources << /Font << /F1 "<<font<<" 0 R >>";if(image_id)dict<<" /XObject << /Im1 "<<image_id<<" 0 R >>";dict<<" >> /Contents "<<content<<" 0 R >>";const auto value=dict.str();page_ids.push_back(add({{value.begin(),value.end()}}));}
std::ostringstream kids;for(int id:page_ids)kids<<id<<" 0 R ";const auto tree="<< /Type /Pages /Count "+std::to_string(page_ids.size())+" /Kids [ "+kids.str()+"] >>";objects[page_tree-1].bytes={tree.begin(),tree.end()};const auto cat="<< /Type /Catalog /Pages "+std::to_string(page_tree)+" 0 R >>";objects[catalog-1].bytes={cat.begin(),cat.end()};std::vector<std::uint8_t> out={'%','P','D','F','-','1','.','7','\n','%',0xe2,0xe3,0xcf,0xd3,'\n'};std::vector<std::size_t> offsets={0};for(std::size_t i=0;i<objects.size();++i){offsets.push_back(out.size());const auto h=std::to_string(i+1)+" 0 obj\n";out.insert(out.end(),h.begin(),h.end());out.insert(out.end(),objects[i].bytes.begin(),objects[i].bytes.end());const std::string end="\nendobj\n";out.insert(out.end(),end.begin(),end.end());}const auto xref=out.size();std::ostringstream x;x<<"xref\n0 "<<objects.size()+1<<"\n0000000000 65535 f \n";for(std::size_t i=1;i<offsets.size();++i)x<<std::setw(10)<<std::setfill('0')<<offsets[i]<<" 00000 n \n";x<<"trailer\n<< /Size "<<objects.size()+1<<" /Root "<<catalog<<" 0 R >>\nstartxref\n"<<xref<<"\n%%EOF\n";const auto tail=x.str();out.insert(out.end(),tail.begin(),tail.end());fs::write_bytes_atomic(path,out);}
}  // namespace abzar
